name: Core
on:
  pull_request:
    # branches:
    #   - main
    paths:
      - 'core/**'

jobs:
  quality-check:
    name: Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # with:
        #   fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.6'
      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.56.2
          args: --out-format checkstyle:lint-report.xml,github-actions --timeout 2m --tests=false
          working-directory: './core'
      - name: Test
        run: go test -v -timeout 30s -count=1 ./... -coverprofile=test-report.out
        working-directory: './core'
